version: '3'
services:
    db:
        container_name: mysql-db
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: jsnews
            MYSQL_DATABASE: jsnews
            MYSQL_USER: jsnews
            MYSQL_PASSWORD: jsnews
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
