apiVersion: apps/v1
kind: Deployment
metadata:
    name: jsnews
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jsnews
    template:
        metadata:
            labels:
                app: jsnews
        spec:
            containers:
                - name: jsnews
                  image: $JSNEWS_IMAGE
                  ports:
                      - containerPort: 3000
            imagePullSecrets:
                - name: $JSNEWS_DOCKER_REGISTRY
    strategy:
        type: Recreate
---
apiVersion: v1
kind: Service
metadata:
    name: jsnews-service
spec:
    selector:
        app: jsnews
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:8
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: $DB_PASSWORD
                      - name: MYSQL_DATABASE
                        value: $DB_DATABASE
                      - name: MYSQL_USER
                        value: $DB_USERNAME
                      - name: MYSQL_PASSWORD
                        value: $DB_PASSWORD
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
            volumes:
                - name: mysql-data
                  persistentVolumeClaim:
                      claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    selector:
        app: mysql
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-external-service
spec:
    type: NodePort
    selector:
        app: mysql
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: traefik-routers
    annotations:
        spec.ingressClassNam: traefik
spec:
    rules:
        - host: jsne.ws
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: jsnews-service
                            port:
                                number: 80
