apiVersion: apps/v1
kind: Deployment
metadata:
    name: jsnews
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jsnews
    template:
        metadata:
            labels:
                app: jsnews
        spec:
            containers:
                - name: jsnews
                  image: JSNEWS_IMAGE_PLACE
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          cpu: '1'
                          memory: '512Mi'
                  livenessProbe:
                      httpGet:
                          path: '/api/health/'
                          port: 3000
                      initialDelaySeconds: 1
---
apiVersion: v1
kind: Service
metadata:
    name: jsnews-service
spec:
    selector:
        app: jsnews
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: traefik-routers
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
        - host: jsne.ws
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: jsnews-service
                            port:
                                number: 80
