type Query {
    user: User
    posts: [Post]
}

type Post implements Node {
    id: ID!
    title: String!
    content: String!
}

type User implements Node {
    id: ID!
    name: String!
}

interface Node {
    id: ID!
}
