name: Deploy

on:
    - workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout secret env
              uses: actions/checkout@v4
              with:
                  repository: skt-t1-byungi/jsnews-secret
                  token: ${{ secrets.JSNEWS_SECRET_GITHUB_TOKEN }}
                  ref: main
                  path: secret
            - name: Set env
              run: cp secret/prod/.env .env && rm -rf secret
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKER_REGISTRY_NAME }}/jsnews
            - name: Docker login
              uses: docker/login-action@v3
              with:
                  registry: https://${{ secrets.DOCKER_REGISTRY_NAME }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  labels: ${{ steps.meta.outputs.labels }}
                  tags: ${{ secrets.DOCKER_REGISTRY_NAME }}/jsnews:latest
            - name: Install kubectl
              uses: azure/setup-kubectl@v3
            - name: Checkout secret kubeconfig
              uses: actions/checkout@v4
              with:
                  repository: skt-t1-byungi/jsnews-secret
                  token: ${{ secrets.JSNEWS_SECRET_GITHUB_TOKEN }}
                  ref: main
                  path: secret
            - name: Deploy
              env:
                  JSNEWS_IMAGE: ${{ secrets.DOCKER_REGISTRY_NAME }}/jsnews:latest
              run: |
                  mkdir -p ~/.kube
                  cp secret/prod/kubeconfig ~/.kube/config
                  set -a
                  source secret/prod/.env
                  set +a
                  envsubst < k3s.yml | kubectl apply -f -
                  kubectl rollout restart deployment jsnews
