name: Deploy

on:
    - workflow_dispatch

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout secret repo
              uses: actions/checkout@v4
              with:
                  repository: skt-t1-byungi/jsnews-secret
                  token: ${{ secrets.JSNEWS_SECRET_GITHUB_TOKEN }}
                  ref: main
                  path: secret
                  sparse-checkout: 'prod/.env'
            - name: Set env
              run: cp secret/prod/.env .env
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKER_REGISTRY_NAME }}/jsnews
            - name: Docker login
              uses: docker/login-action@v3
              with:
                  registry: https://${{ secrets.DOCKER_REGISTRY_NAME }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  labels: ${{ steps.meta.outputs.labels }}
                  tags: ${{ steps.meta.outputs.tags }}
